version: "3.9"

networks:
  app-net:
    driver: bridge

services:
  web:
    build: ./
    command: python base/manage.py runserver 0.0.0.0:8888
    volumes:
        - .:/usr/src/app/
    networks:
      - app-net
    ports:
        - 8888:8888
    env_file:
        - ./.env
    restart: unless-stopped
