# Generated by Django 3.2.5 on 2023-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
